"""The practice: one lawyer, his junior, two judges, five cases.

Three cases are about one piece of land. Ramesh Gorle and Srinivas Bandaru, school friends, bought 4.20 acres near
Bheemili beach together in 2011. In 2024 Seabreeze Resorts wanted the land for a resort. Srinivas wanted to sell;
Ramesh would not (his father is buried in the mango grove on the east side). Srinivas signed a sale agreement with
the company for the whole plot anyway.

  C1  Ramesh vs Srinivas        who owns how much            before Padmavathi (gentle)
  C2  Seabreeze vs Srinivas & Ramesh   enforce the sale agreement    before Murthy (impatient)
  C3  Ramesh vs Seabreeze       stop the company fencing the land   before Murthy
  C4  landlady vs tenant        eviction, unrelated          before Padmavathi
  C5  printer vs school         unpaid bills, unrelated      before Murthy

Hearing dates are snapped to the next Mon-Fri by build.py. "{NEXT}" in an order sheet becomes the next hearing date.
"""

ADVOCATE = {
    "name": "Aditya Varma", "short": "Aditya", "enrolment_no": "AP/2231/2013", "city": "Visakhapatnam",
    "chamber_address": "D.No. 9-12-4, Opp. District Court, Kotha Road, Visakhapatnam 530001",
    "practice": "Civil litigation: property, partition, specific performance, injunctions, rent and recovery suits",
    "assistant": {"name": "Divya Kanaka", "short": "Divya", "role": "junior advocate (enrolled 2024)"},
}

JUDGES = [
    {"id": "J1", "name": "Sri P. Suryanarayana Murthy", "short": "Murthy sir",
     "court": "Principal Senior Civil Judge", "court_hall": "Court Hall 3, District Court Complex", "level": "District",
     "temperament": "Impatient. Hates anything irregular: late filings, missing indexes, unserved copies, repeated adjournments.",
     "habits": ["refuses documents filed without an index or without serving copies",
                "imposes costs on the third adjournment by the same side",
                "says 'last opportunity' on the second"]},
    {"id": "J2", "name": "Smt. G. Padmavathi", "short": "Padmavathi madam",
     "court": "II Additional Senior Civil Judge", "court_hall": "Court Hall 6, District Court Complex", "level": "District",
     "temperament": "Gentle and forgiving. Grants time readily, rarely imposes costs, pushes parties towards mediation.",
     "habits": ["suggests mediation whenever parties are family or old friends",
                "grants a second chance without costs, with a polite warning"]},
]

COUNSEL = [
    {"id": "OC1", "name": "Sri M. Harinath", "chamber": "Harinath & Co., Daba Gardens",
     "style": "Old-school, polite, slow. Asks for time often."},
    {"id": "OC2", "name": "Sri V. Harsha Vardhan", "chamber": "Vardhan Legal LLP (corporate)",
     "style": "Sharp, aggressive, files in bulk at the last minute."},
    {"id": "OC3", "name": "Smt. K. Sundari", "chamber": "Sundari Associates, Gajuwaka", "style": "Practical, settles."},
    {"id": "OC4", "name": "Sri T. Bhaskar", "chamber": "Bhaskar Law Chambers, MVP Colony",
     "style": "Overbooked. Adjourns citing illness or other courts."},
]

CLIENTS = [
    {"id": "CL1", "name": "Ramesh Gorle", "type": "individual, mango and cashew farmer, 52",
     "note": "won't sell the land; his father's grave is in the mango grove"},
    {"id": "CL2", "name": "Lakshmi Kantham Peddinti", "type": "individual, widow, landlady", "note": "calls Divya every week"},
    {"id": "CL3", "name": "Vijaya Offset Printers (prop. Murali Krishna Pydi)", "type": "small business"},
]

LAND = "Ac. 4.20 cents in Sy. No. 112/2, Mangamaripeta village, Bheemunipatnam mandal"

CASES = [
    {"id": "C1", "case_number": "O.S. No. 214 of 2024", "judge_id": "J2", "opposing_counsel_id": "OC1", "client_id": "CL1",
     "title": "Ramesh Gorle vs Srinivas Bandaru", "short_name": "Gorle partition", "represents": "plaintiff",
     "nature": "suit for partition and declaration of half share", "kind": "suit", "filed_on": "2024-08-19",
     "summary": f"Ramesh claims half of {LAND}; Srinivas claims 70% because he says he paid Rs. 21 lakh of the Rs. 30 lakh price."},
    {"id": "C2", "case_number": "O.S. No. 57 of 2025", "judge_id": "J1", "opposing_counsel_id": "OC2", "client_id": "CL1",
     "title": "Seabreeze Resorts & Hospitality Pvt. Ltd. vs Srinivas Bandaru & Ramesh Gorle", "short_name": "Seabreeze SP suit",
     "represents": "defendant 2", "nature": "suit for specific performance of agreement of sale dated 18.09.2024", "kind": "suit",
     "filed_on": "2025-01-20",
     "summary": "Company sues on an agreement Srinivas alone signed for the whole 4.20 acres; Ramesh never signed."},
    {"id": "C3", "case_number": "O.S. No. 131 of 2025", "judge_id": "J1", "opposing_counsel_id": "OC2", "client_id": "CL1",
     "title": "Ramesh Gorle vs Seabreeze Resorts & Hospitality Pvt. Ltd.", "short_name": "Seabreeze injunction",
     "represents": "plaintiff", "nature": "suit for permanent injunction, with I.A. No. 612 of 2025 for temporary injunction",
     "kind": "suit", "filed_on": "2025-04-21",
     "summary": "Company workers put up fencing poles on the land on 14.04.2025; Ramesh sued to stop them."},
    {"id": "C4", "case_number": "O.S. No. 302 of 2025", "judge_id": "J2", "opposing_counsel_id": "OC3", "client_id": "CL2",
     "title": "Lakshmi Kantham Peddinti vs Nagaraju Kotla", "short_name": "Tiffin centre eviction", "represents": "plaintiff",
     "nature": "suit for eviction and arrears of rent", "kind": "suit", "filed_on": "2025-06-09",
     "summary": "Tenant running 'Sri Durga Tiffins' in the ground-floor shop at Dwaraka Nagar owes 11 months' rent (Rs. 1,98,000)."},
    {"id": "C5", "case_number": "O.S. No. 88 of 2025", "judge_id": "J1", "opposing_counsel_id": "OC4", "client_id": "CL3",
     "title": "Vijaya Offset Printers vs Greenfield Public School", "short_name": "Greenfield school recovery",
     "represents": "plaintiff", "nature": "suit for recovery of Rs. 6,84,500 with interest", "kind": "suit",
     "filed_on": "2025-02-24",
     "summary": "Printer supplied textbooks and notebooks for 2023-24; school paid nothing on 14 invoices."},
]

DEMO_DAY = "2026-10-05"

# ------------------------------------------------------------------ hearings
# fmt: hw = photo of a handwritten page (by Aditya or Divya), txt = Divya's typed day notes, docx = Aditya's case note
# scan: True = a certified copy of the order sheet was obtained after this hearing
H = lambda d, fmt, by, order, note, scan=False: {"date": d, "fmt": fmt, "by": by, "order": order, "note": note, "scan": scan}

HEARINGS = {
"C3": [
    H("2025-04-23", "hw", "Aditya",
      "Counsel for petitioner heard. Ad-interim order of status quo as on date regarding the suit schedule property till {NEXT}. Notice to respondent. Petitioner to comply with O.39 R.3 CPC.",
      "Seabreeze injunction (OS 131/25) - IA 612. Got status quo till next date. Murthy sir returned our paper book once - index had no page numbers! Fixed it in the corridor in 10 min. Never again. Divya: O.39 R.3 compliance by courier TODAY, keep the postal receipts.", True),
    H("2025-05-07", "hw", "Divya",
      "Respondent appeared through counsel. Time sought for counter. Two weeks granted, no further time. Status quo to continue till {NEXT}.",
      "Seabreeze inj - Harsha Vardhan appeared for company. Asked 4 weeks for counter, judge gave 2 and said 'no further time, counsel, your client is a company not a farmer'. Status quo extended."),
    H("2025-05-21", "txt", "Divya",
      "Counter filed by respondent. Petitioner to file rejoinder, if any. Status quo to continue till {NEXT}.",
      "Seabreeze inj - counter filed. Para 6 of counter: 'the respondent has not undertaken any construction activity whatsoever on the schedule land; only a survey was conducted.' Sir says keep this line safe. Sir told court we will file rejoinder in 10 days."),
    H("2025-06-04", "hw", "Aditya",
      "Rejoinder filed on 02.06.2025. Arguments of both sides heard in part. Petitioner to produce photographs with dates. Status quo to continue. Call on {NEXT}.",
      "Seabreeze inj - rejoinder filed 2 June, on time (diary no. 2291). Part heard. Murthy sir wants photos WITH dates - Ramesh's phone photos of the poles, get the originals + print with EXIF date. Harsha argued 'only survey pegs'."),
    H("2025-06-18", "hw", "Aditya",
      "I.A. No. 612 of 2025 allowed. Respondent, its men and agents restrained from making any construction or erecting any fencing in the petition schedule property pending disposal of the suit. Suit posted for written statement on {NEXT}.",
      "Seabreeze inj - WON the IA!! Temp injunction till disposal. Judge said the photos dated 14.04.2025 show fencing poles, not survey pegs. Called Ramesh garu, he cried on the phone. Harsha will appeal? Watch for CMA.", True),
    H("2025-08-06", "txt", "Divya",
      "Written statement filed by defendant. For framing of issues on {NEXT}.",
      "Seabreeze inj - WS filed. No CMA against the IA order so far (checked at CMA section). For issues."),
    H("2025-09-17", "hw", "Divya",
      "Issues framed. Plaintiff to file list of witnesses within 15 days. For plaintiff's evidence on {NEXT}.",
      "Seabreeze inj - issues framed (4 issues). Our list of witnesses within 15 days - due 2 Oct. Witnesses: Ramesh, VRO Appala Naidu (summons), neighbour Sanyasi Rao."),
    H("2025-11-12", "docx", "Aditya",
      "PW1 examined in chief by affidavit. Ex.A1 to A7 marked. For cross-examination of PW1 on {NEXT}.",
      "PW1 Ramesh Gorle chief affidavit filed. Marked: Ex.A1 sale deed doc. no. 3417/2011, Ex.A2 1-B ROR extract, Ex.A3 encumbrance certificate, Ex.A4 police petition acknowledgment 15.04.2025, Ex.A5 photos (6) of fencing poles dated 14.04.2025, Ex.A6 letter of understanding 2016, Ex.A7 legal notice of company dated 12.11.2024. Prepare Ramesh for cross: Harsha will suggest he agreed to sell at the Novotel meeting.", True),
    H("2026-01-21", "hw", "Aditya",
      "PW1 cross-examined by counsel for defendant. For PW2 on {NEXT}.",
      "Seabreeze inj - PW1 cross. Harsha put it to Ramesh that he agreed to sell at the Novotel meeting in Sept 2024. Ramesh: 'Never. My father is buried in the mango grove on the east side. I will not sell that land for any price.' Held up well. Harsha also suggested the poles were for survey - Ramesh: 'survey people don't dig 2 feet and put cement.'"),
    H("2026-03-11", "hw", "Aditya",
      "Memo filed by defendant without serving copy on the other side is not received. Defendant is directed to serve copies before filing any memo. Counsel for plaintiff reports that stones on the boundary were removed; defendant is cautioned to strictly comply with the injunction order. For PW2 on {NEXT}.",
      "Seabreeze inj - Harsha tried to file a memo (something about 'survey for revenue purposes') without giving us a copy. Murthy sir threw it back: 'this is not how it is done in my court, serve copy first.' Also told him about boundary stones removed last week (Ramesh's info) - judge cautioned company on record. Good day."),
    H("2026-06-10", "txt", "Divya",
      "PW2 examined and cross-examined. For defendant's evidence on {NEXT}.",
      "Seabreeze inj - PW2 VRO Appala Naidu (summoned). Said he inspected the land on 14.04.2025 on Tahsildar's instructions after a complaint; saw about 40 cement fencing poles along the west boundary; workers told him they were Seabreeze people. Cross: Harsha asked if he saw any company board - VRO said 'no board, but a Seabreeze jeep AP 31 CX 4417 was parked there.' Very useful."),
    H("2026-08-19", "hw", "Aditya",
      "DW1 examined in chief by affidavit. Ex.B1 to B3 marked. Cross-examination of DW1 in part. For further cross-examination of DW1 on {NEXT}.",
      "Seabreeze inj - DW1 Kiran Kumar Sabbavarapu (company site manager). Chief: 'no work at all before permissions.' In cross he admitted 'survey pegs and some poles' were put in April 2025. Also admitted jeep AP 31 CX 4417 is a company vehicle. Continue cross on 5 Oct - confront him with para 3 of the company's own plaint in OS 57/25 (they 'commenced preliminary works in April 2025')! Get certified copy of that plaint - Divya.", True),
],
"C2": [
    H("2025-04-09", "hw", "Aditya",
      "D1 and D2 appeared through counsel. Time sought for written statements. For written statements of D1 and D2 on {NEXT}.",
      "Seabreeze SP suit (OS 57/25) - first date. Company served us the agreement copy today (18.09.2024 agreement - Srinivas signed for 'himself and as agent of Ramesh'. Ramesh's signature column is BLANK). Harinath for Srinivas. Time for WS."),
    H("2025-06-11", "hw", "Aditya",
      "Written statement of D1 filed. D2 seeks time for written statement. Time granted as a last opportunity. For written statement of D2 on {NEXT}.",
      "Seabreeze SP - Srinivas's WS filed: he SUPPORTS the company. Says he and Ramesh are 'equal co-owners' and that Ramesh 'orally agreed' at the Novotel meeting in Sept 2024. EQUAL co-owners - note this. Our WS not ready (my fault, Ramesh came late with papers). Murthy sir: 'last opportunity, counsel.'", True),
    H("2025-07-09", "hw", "Aditya",
      "Written statement of D2 filed. Plaintiff filed 14 documents without a list and without serving copies; the documents are not received. Costs of Rs. 2,000 imposed on plaintiff payable to D2. Plaintiff to file the documents with a proper list after serving copies. For documents on {NEXT}.",
      "Seabreeze SP - our WS filed (denies agreement, no GPA ever given, 2016 letter of understanding). Harsha dumped 14 documents on the table without a list - Murthy sir refused to receive them and put Rs 2,000 costs on the company, payable to Ramesh! 'File properly, with an index, and serve copies.'"),
    H("2025-09-03", "txt", "Divya",
      "Documents filed with list, copies served. For framing of issues on {NEXT}.",
      "Seabreeze SP - company refiled documents properly with list. Costs Rs 2,000 paid to us by DD (handed over to Ramesh garu). For issues."),
    H("2025-10-15", "hw", "Divya",
      "Issues framed. For plaintiff's evidence on {NEXT}.",
      "Seabreeze SP - issues framed. Issue 3: 'Whether D1 had authority to agree to sell the share of D2?' Sir happy with this issue."),
    H("2025-12-10", "docx", "Aditya",
      "PW1 examined in chief by affidavit. Ex.A1 to A9 marked. For cross-examination of PW1 on {NEXT}.",
      "PW1 Rohan Mehta, director of Seabreeze. Ex.A1 agreement of sale dt. 18.09.2024 marked. Plaint para 3 and his affidavit: the company 'paid advance of Rs. 25,00,000 to D1 and commenced preliminary works on the site in April 2025'. COMPARE: counter in OS 131/25 para 6 says 'no construction activity whatsoever; only a survey'. Use this in both cases.", True),
    H("2026-02-04", "hw", "Aditya",
      "PW1 cross-examined by counsel for D1 and D2. For PW2 on {NEXT}.",
      "Seabreeze SP - PW1 cross. Admitted: (1) Ramesh did not sign Ex.A1; (2) company knew from the 1-B that land stood in both names; (3) no GPA from Ramesh was ever shown to them; (4) the Rs 25 lakh cheque went only to Srinivas's account. When asked why they started 'preliminary works' before a sale deed - 'on legal advice.' Ha."),
    H("2026-04-08", "hw", "Divya",
      "Counsel for plaintiff reported to be held up in another court. Adjourned as a last chance. For PW2 on {NEXT}.",
      "Seabreeze SP - Harsha's junior said sir is held up in High Court at Amaravati. Murthy sir very annoyed: 'Last chance. Next time I will close the evidence.'"),
    H("2026-05-13", "hw", "Aditya",
      "Plaintiff's evidence closed. DW1 (D1) examined in chief. For cross-examination of DW1 on {NEXT}.",
      "Seabreeze SP - company closed evidence. Srinivas (D1) as DW1: 'Ramesh and I are EQUAL owners, 50-50, each 2.10 acres.' Divya pls check - in OS 214/24 before Padmavathi madam his WS says he owns 70%!! Get certified copy of this deposition for use in OS 214.", True),
    H("2026-07-15", "hw", "Aditya",
      "DW1 cross-examined by counsel for D2. For D2's evidence on {NEXT}.",
      "Seabreeze SP - DW1 cross. Confronted Srinivas with the 2016 letter (Ex.B3) - admitted his signature. The letter says neither will sell without the other's written consent. He said 'that was a friendly letter.' Also admitted he kept the Rs 25 lakh."),
    H("2026-09-02", "hw", "Aditya",
      "Plaintiff filed I.A. No. 1187 of 2026 under O.6 R.17 CPC for amendment of plaint. Counsel for D2 undertakes to file objections by 30.09.2026. For objections and hearing on the I.A. on {NEXT}.",
      "Seabreeze SP - company wants to AMEND plaint to ask for Srinivas's half only (alternative relief). Means they know they'll lose on Ramesh's half. I undertook to file objections by 30 Sept. Divya: draft objections by 20 Sept, need certified copy of EC and 1-B again (latest). Ramesh garu - explain on phone, he'll panic.", True),
],
"C1": [
    H("2025-05-14", "hw", "Aditya",
      "Counsel for defendant seeks time for written statement. Four weeks granted. For written statement on {NEXT}.",
      "Gorle partition (OS 214/24) - Harinath asked time for WS AGAIN (3rd time since filing). Padmavathi madam smiled, gave 4 weeks, 'please file by next date, Mr. Harinath.' No costs. She is too kind."),
    H("2025-06-25", "hw", "Aditya",
      "Written statement filed by defendant. For framing of issues on {NEXT}.",
      "Gorle partition - Srinivas's WS: claims 70% share - says he paid Rs 21 lakh and Ramesh only Rs 9 lakh in 2011. Says the 2016 letter was 'only for family peace' and not binding. Ramesh says each paid 15 lakh - his SBI Dwaraka Nagar statement of 2011 will show the transfer. Get it.", True),
    H("2025-08-13", "hw", "Divya",
      "Parties present. The court is of the view that the dispute may be resolved amicably. Referred to the Mediation Centre, District Court, Visakhapatnam. Report by {NEXT}.",
      "Gorle partition - madam talked to both parties directly. 'You were school friends, sit together once.' Referred to mediation. Ramesh agreed, Srinivas reluctant."),
    H("2025-10-08", "txt", "Divya",
      "Mediation report received: failed. For framing of issues on {NEXT}.",
      "Gorle partition - mediation failed. Mediator's note: 'D wants the entire property sold to a third party; P not willing to sell under any circumstances.' Madam said 'Sad, two old friends. Let us proceed then.'"),
    H("2025-11-26", "hw", "Aditya",
      "Issues framed. For plaintiff's evidence on {NEXT}.",
      "Gorle partition - issues: (1) is P entitled to half share; (2) did D pay Rs 21 lakh of the price; (3) is the 2016 letter binding. Plaintiff's evidence next.", True),
    H("2026-01-07", "docx", "Aditya",
      "PW1 examined in chief by affidavit. Ex.A1 to A5 marked. For cross-examination of PW1 on {NEXT}.",
      "PW1 Ramesh Gorle chief. Ex.A1 sale deed 3417/2011, Ex.A2 1-B ROR extract (2.10 acres each), Ex.A3 letter of understanding 2016, Ex.A4 SBI Dwaraka Nagar statement showing Rs. 15,00,000 transferred to the vendor on 02.03.2011, Ex.A5 encumbrance certificate. Madam asked if the parties still talk. Ramesh: 'only through lawyers now.'"),
    H("2026-02-18", "hw", "Aditya",
      "PW1 cross-examined. Plaintiff seeks time to summon PW2. For PW2 on {NEXT}.",
      "Gorle partition - PW1 cross by Harinath. Ramesh firm: 'each of us paid 15 lakh, I paid from SBI, he paid in cash to the vendor.' Harinath suggested the cash was 21 lakh - denied. Summons to VRO for next date - Divya to take out summons THIS WEEK."),
    H("2026-03-25", "hw", "Aditya",
      "PW2 not present; summons not taken out. Adjourned at the request of plaintiff. For PW2 on {NEXT}.",
      "Gorle partition - VRO summons NOT taken out. Divya forgot, I didn't check. Embarrassing. Madam: 'these things happen, but please don't repeat it, Mr. Varma.' No costs. Murthy sir would have closed our evidence. RULE: every Monday check summons list."),
    H("2026-06-03", "txt", "Divya",
      "PW2 examined and cross-examined. Plaintiff's evidence closed. For defendant's evidence on {NEXT}.",
      "Gorle partition - PW2 VRO Appala Naidu (same VRO as in Seabreeze injunction). 1-B ROR shows 2.10 acres each in both names since 2012 mutation. Ramesh's family cultivates mango and cashew on the east half; the grave of Ramesh's father is on the east side under the mango trees. Cross: Harinath asked who pays land tax - VRO: 'both, separately, for 2.10 each.'", True),
    H("2026-07-22", "hw", "Aditya",
      "DW1 examined in chief and cross-examined in part. For further cross-examination of DW1 on {NEXT}.",
      "Gorle partition - DW1 Srinivas: 70% claim again. In cross I put his deposition of 13.05.2026 in OS 57/25 (before Murthy sir) - 'Ramesh and I are EQUAL owners, 50-50.' He fumbled: 'that is a different case.' Madam wrote it down carefully. Need CERTIFIED copy of that deposition to mark it - Divya."),
    H("2026-09-09", "hw", "Divya",
      "DW2 absent. Counsel for defendant seeks time. Adjourned as a last chance. For DW2 on {NEXT}.",
      "Gorle partition - DW2 (Srinivas's brother-in-law Pothina Venkat, receipt witness) absent. Harinath sought time. Madam: 'last chance' but no costs. Next 14 Oct."),
],
"C4": [
    H("2025-07-02", "hw", "Divya",
      "Defendant appeared through counsel. Time for written statement. For written statement on {NEXT}.",
      "Tiffin centre (OS 302/25) - Sundari madam for tenant Nagaraju. Time for WS."),
    H("2025-08-20", "hw", "Aditya",
      "Written statement filed. Defendant directed to deposit the admitted arrears within eight weeks. For deposit on {NEXT}.",
      "Tiffin centre - WS: tenant says landlady refused to accept rent after March 2024, will deposit. Padmavathi madam directed deposit of arrears in 8 weeks. Lakshmi garu upset it's not immediate eviction - explained."),
    H("2025-10-29", "txt", "Divya",
      "Defendant deposited Rs. 60,000. Further time of six weeks granted to deposit the balance. For deposit on {NEXT}.",
      "Tiffin centre - only Rs 60,000 deposited of 1,98,000. Madam gave 6 more weeks, gently. Lakshmi garu called twice after court."),
    H("2026-01-28", "hw", "Divya",
      "Defendant deposited a further sum of Rs. 50,000. Parties are advised to explore settlement. For report on {NEXT}.",
      "Tiffin centre - another 50k deposited (total 1,10,000). Madam suggested both sides settle - tenant wants time to shift the tiffin centre."),
    H("2026-03-18", "hw", "Aditya",
      "Counsel on both sides report that settlement talks are in progress. For compromise on {NEXT}.",
      "Tiffin centre - Nagaraju wants 8 months to vacate, Lakshmi garu wants 3. Middle: vacate by 30.11.2026, balance 88,000 in instalments of 15,000 by the 10th of each month."),
    H("2026-05-06", "docx", "Aditya",
      "Joint compromise memo filed and recorded. Defendant to vacate the plaint schedule premises on or before 30.11.2026 and pay the balance arrears of Rs. 88,000 in monthly instalments of Rs. 15,000 on or before the 10th of every month from June 2026. Suit decreed in terms of the compromise. No costs.",
      "Compromise recorded. Tenant to vacate by 30.11.2026. Balance Rs 88,000 in instalments of Rs 15,000 by the 10th of each month from June 2026 (6 instalments, last one Rs 13,000 in Nov). If any instalment is missed we can execute the decree for eviction at once - clause 4 of the memo.", True),
],
"C5": [
    H("2025-06-16", "hw", "Divya",
      "Defendant appeared through counsel. Time for written statement. For written statement on {NEXT}.",
      "Greenfield school (OS 88/25) - Bhaskar for school. Time for WS."),
    H("2025-07-28", "hw", "Divya",
      "Written statement not filed. Time sought. Adjourned with a direction to file the written statement positively by the next date. For written statement on {NEXT}.",
      "Greenfield - WS not filed. Bhaskar's junior said sir is unwell. Murthy sir: 'positively by next date.'"),
    H("2025-09-08", "hw", "Aditya",
      "Written statement filed with a petition to condone delay. Delay condoned subject to costs of Rs. 1,000 payable to plaintiff. For framing of issues on {NEXT}.",
      "Greenfield - WS filed late with delay petition; Murthy sir condoned delay but Rs 1,000 costs to us. WS says books had 'printing defects', but they never returned a single book!", True),
    H("2025-11-03", "txt", "Divya",
      "Issues framed. For plaintiff's evidence on {NEXT}.",
      "Greenfield - issues framed. Murali garu's chief affidavit to be ready - invoices, delivery challans signed by school clerk, 3 reminder letters."),
    H("2026-01-12", "docx", "Aditya",
      "PW1 examined in chief by affidavit. Ex.A1 to A20 marked. For cross-examination of PW1 on {NEXT}.",
      "PW1 Murali Krishna Pydi chief. Ex.A1-A14 invoices (total Rs. 6,84,500), Ex.A15-A17 delivery challans signed by school office, Ex.A18-A20 reminder letters. Purchase order dt. 04.04.2023 is Ex.A1 annexure."),
    H("2026-02-23", "hw", "Divya",
      "Counsel for defendant absent. Junior counsel seeks time for cross-examination of PW1. Adjourned. For cross-examination of PW1 on {NEXT}.",
      "Greenfield - Bhaskar absent (1st adjournment for cross). Junior asked time. Granted. Murali garu lost a day of work again."),
    H("2026-04-20", "hw", "Aditya",
      "Counsel for defendant reported to be unwell. Adjourned as a last opportunity for cross-examination of PW1. For cross-examination of PW1 on {NEXT}.",
      "Greenfield - Bhaskar 'unwell' (2nd time). Murthy sir: 'LAST opportunity.' Saw Bhaskar in the bar association canteen at 1.30 pm the same day. Noting it.", True),
    H("2026-06-22", "hw", "Aditya",
      "Counsel for defendant again seeks adjournment. Request rejected. Cross-examination of PW1 treated as nil. Costs of Rs. 3,000 imposed on defendant payable to plaintiff. For defendant's evidence on {NEXT}.",
      "Greenfield - 3rd adjournment request. Murthy sir REJECTED it, cross of PW1 closed as nil, Rs 3,000 costs. Said: 'If counsel is unwell every alternate hearing, the client should engage another counsel.' Same as he did in Seabreeze (Rs 2,000 costs for irregular filing). His pattern: 2nd time 'last opportunity', 3rd time costs."),
    H("2026-08-03", "txt", "Divya",
      "DW1 examined in chief by affidavit. For cross-examination of DW1 on {NEXT}.",
      "Greenfield - DW1 school correspondent K. Jagan Mohan. Chief: printing defects, pages missing in class 7 maths books."),
    H("2026-09-14", "hw", "Aditya",
      "DW1 cross-examined. Evidence on both sides closed. For arguments on {NEXT}.",
      "Greenfield - DW1 cross. Admitted: all books were distributed to students in June 2023; not one returned; no written complaint ever sent to the printer. For arguments on 5 Oct - written arguments ready by 1 Oct (Divya drafts, I finalise).", True),
],
}

FINAL_NEXT = {"C1": "2026-10-14", "C2": DEMO_DAY, "C3": DEMO_DAY, "C4": "", "C5": DEMO_DAY}

# Notes that don't belong to a hearing (phone calls, office work)
EXTRA_NOTES = [
    {"date": "2025-04-21", "fmt": "hw", "by": "Aditya", "case_ids": ["C3"],
     "text": "Ramesh Gorle came with Divya at 8 am. Company men put cement poles on the west side of the land yesterday (14th) - 40 poles approx. Ramesh gave police petition at Bheemunipatnam PS on 15th, only acknowledgment given, no FIR. Filing suit for injunction today + IA. Ramesh: 'nanna's grave is there sir, they will bulldoze it.'"},
    {"date": "2026-09-15", "fmt": "txt", "by": "Divya", "case_ids": ["C4"],
     "text": "Tiffin centre - Lakshmi garu called. September instalment (Rs 15,000, due 10th) NOT paid. August one came late on 14th. Clause 4 of compromise memo: we can file execution for eviction at once. Asked sir - he said send a letter to Sundari madam first, then EP if not paid by 25th."},
    {"date": "2026-09-24", "fmt": "txt", "by": "Divya", "case_ids": ["C2"],
     "text": "Seabreeze SP - objections to IA 1187/2026 (amendment): draft 60% done. Waiting for fresh EC from SRO Bheemunipatnam (applied 16 Sept, not given yet). Due to file by 30 Sept as per sir's undertaking. Will tell sir tomorrow."},
]

# ------------------------------------------------------------------ documents (government, agreements, friends)
# kind: doc = typed/printed page(s); letter = handwritten letter on plain paper; chat = WhatsApp export (.txt)
DOCS = [
    {"uploaded": "2025-04-09", "case_ids": ["C2", "C3"], "name": "Agreement_of_Sale_Seabreeze_18-09-2024", "kind": "doc",
     "stamp_paper": ["INDIA NON JUDICIAL", "ANDHRA PRADESH", "Rs. 100   ONE HUNDRED RUPEES", "Sl. No. 44721   Date: 16-09-2024   Stamp Vendor: B. Ramana Kumari, Lic. No. 12/2019"],
     "sign": ["Srinivas Bandaru (VENDOR, for himself and as agent of Ramesh Gorle)", "(unsigned) Ramesh Gorle (VENDOR)",
              "Rohan Mehta, Director, for Seabreeze Resorts & Hospitality Pvt. Ltd. (PURCHASER)", "Witness 1: P. Venkat, Gajuwaka"],
     "pages": [[
         ("h", "AGREEMENT OF SALE"),
         ("p", "This Agreement of Sale is made and executed at Visakhapatnam on this the 18th day of September, 2024 BETWEEN:"),
         ("p", "1. Sri Srinivas Bandaru, S/o late Appa Rao, aged about 51 years, R/o Flat 402, Sai Towers, MVP Colony, Visakhapatnam, for himself and as agent of Sri Ramesh Gorle, S/o late Suryanarayana, R/o Mangamaripeta village (hereinafter called the VENDORS)"),
         ("p", "AND"),
         ("p", "M/s. Seabreeze Resorts & Hospitality Pvt. Ltd., a company incorporated under the Companies Act, 2013, having its registered office at 3rd Floor, Dolphin Plaza, Siripuram, Visakhapatnam, represented by its Director Sri Rohan Mehta (hereinafter called the PURCHASER)."),
         ("p", "WHEREAS the Vendors are the absolute owners and possessors of agricultural land admeasuring Ac. 4.20 cents in Sy. No. 112/2, Mangamaripeta village, Bheemunipatnam mandal, Visakhapatnam district, having purchased the same under registered sale deed Doc. No. 3417/2011 dated 02.03.2011 of SRO Bheemunipatnam, more fully described in the Schedule hereunder."),
     ], [
         ("p", "NOW THIS AGREEMENT WITNESSETH AS FOLLOWS:"),
         ("p", "1. The total sale consideration is fixed at Rs. 4,20,00,000/- (Rupees Four Crores Twenty Lakhs only) at the rate of Rs. 1,00,00,000/- per acre."),
         ("p", "2. The Purchaser has this day paid a sum of Rs. 25,00,000/- (Rupees Twenty Five Lakhs only) by cheque No. 118804 dated 18.09.2024 drawn on HDFC Bank, Siripuram branch, in favour of Sri Srinivas Bandaru, the receipt of which the Vendors hereby acknowledge."),
         ("p", "3. The balance of Rs. 3,95,00,000/- shall be paid at the time of registration of the sale deed, within six months from this date, subject to the Vendors producing clear title and obtaining conversion of land use (NALA)."),
         ("p", "4. The Vendors shall permit the Purchaser to conduct survey and soil tests on the schedule land pending registration. No construction shall be made before registration."),
         ("p", "5. If the Vendors fail to execute the sale deed, the Purchaser shall be entitled to enforce specific performance of this agreement through a court of law."),
         ("gap", ""),
         ("h", "SCHEDULE"),
         ("p", "All that agricultural land admeasuring Ac. 4.20 cents in Sy. No. 112/2, Mangamaripeta village, Bheemunipatnam mandal. Boundaries: East - Sy. No. 113 (Pydi Appala Raju), West - panchayat road, North - Sy. No. 111, South - beach access road."),
         ("s", "Note: Sri Ramesh Gorle to sign on his return from Srikakulam."),
     ]]},
    {"uploaded": "2025-04-21", "case_ids": ["C1", "C2", "C3"], "name": "Sale_Deed_3417-2011_first_pages", "kind": "doc",
     "stamp_paper": ["INDIA NON JUDICIAL", "ANDHRA PRADESH", "Rs. 1,000   ONE THOUSAND RUPEES", "Sl. No. 08813   Date: 28-02-2011"],
     "stamp": ["SUB-REGISTRAR", "BHEEMUNIPATNAM", "Doc. No. 3417/2011"],
     "sign": ["Kakarla Bhaskara Rao (VENDOR)", "Ramesh Gorle (VENDEE 1)", "Srinivas Bandaru (VENDEE 2)", "Witness: G. Suryanarayana"],
     "pages": [[
         ("h", "SALE DEED"),
         ("p", "This Sale Deed is made and executed at Bheemunipatnam on this the 2nd day of March, 2011, by Sri Kakarla Bhaskara Rao, S/o Narasimha Murthy, aged 64 years, agriculturist, R/o Mangamaripeta (hereinafter called the VENDOR),"),
         ("p", "IN FAVOUR OF (1) Sri Ramesh Gorle, S/o Suryanarayana, aged 37 years, and (2) Sri Srinivas Bandaru, S/o Appa Rao, aged 36 years, both R/o Visakhapatnam (hereinafter jointly called the VENDEES)."),
         ("p", "WHEREAS the Vendor is the absolute owner of agricultural land admeasuring Ac. 4.20 cents in Sy. No. 112/2 of Mangamaripeta village, having inherited the same from his father, and has agreed to sell the same to the Vendees for a total consideration of Rs. 30,00,000/- (Rupees Thirty Lakhs only)."),
     ], [
         ("p", "NOW THIS DEED WITNESSETH that in pursuance of the said agreement and in consideration of Rs. 30,00,000/- paid by the Vendees to the Vendor, as follows: Rs. 15,00,000/- by Vendee 1 through RTGS from State Bank of India, Dwaraka Nagar branch, on 02.03.2011, and Rs. 15,00,000/- by Vendee 2 in cash on this day, the receipt of which the Vendor hereby acknowledges, the Vendor hereby conveys the schedule property to the Vendees jointly, in equal shares, absolutely and forever."),
         ("p", "The Vendor has this day delivered vacant possession of the schedule property to the Vendees."),
         ("h", "SCHEDULE"),
         ("p", "Agricultural land admeasuring Ac. 4.20 cents in Sy. No. 112/2, Mangamaripeta village, Bheemunipatnam mandal, Visakhapatnam district, with mango and cashew trees thereon."),
     ]]},
    {"uploaded": "2025-04-21", "case_ids": ["C1", "C2", "C3"], "name": "Letter_of_understanding_2016", "kind": "letter",
     "text": "Visakhapatnam, 10-01-2016\n\nLetter of understanding between friends\n\nWe, Ramesh Gorle and Srinivas Bandaru, jointly own Ac. 4.20 cents in Sy. No. 112/2 Mangamaripeta, bought in 2011. We both own it EQUALLY, 2.10 acres each. Ramesh's father late Suryanarayana garu is buried in the mango grove on the east side and that portion will always be with Ramesh.\n\nNeither of us will sell, mortgage or agree to sell the land or any part of it without the written consent of the other.\n\nWe write this so that our children also know.\n\nSd/- Ramesh Gorle          Sd/- Srinivas Bandaru\nWitness: Dr. K. Prasad (classmate), Sd/-"},
    {"uploaded": "2025-04-21", "case_ids": ["C1", "C2", "C3"], "name": "WhatsApp Chat with Srinivas", "kind": "chat",
     "text": "[12/08/24, 7:41 PM] Srinivas: Ramesh, Seabreeze people called again. 1 crore per acre ra. 4.2 crores. We will never get this price\n[12/08/24, 7:55 PM] Ramesh: No Srinu. I told you already. Nanna is there\n[12/08/24, 7:56 PM] Srinivas: We can shift the samadhi respectfully, they said they will pay for everything\n[12/08/24, 8:20 PM] Ramesh: Don't talk like that\n[03/09/24, 10:02 AM] Srinivas: Meeting at Novotel on 10th with their director Rohan Mehta. Please come once, just listen\n[03/09/24, 10:40 AM] Ramesh: I will come only to tell them no\n[10/09/24, 9:15 PM] Srinivas: You didn't say no clearly in the meeting. They are preparing agreement\n[10/09/24, 9:18 PM] Ramesh: I said clearly I won't sell. You heard it\n[10/09/24, 9:18 PM] Ramesh: Don't sign anything for me\n[19/09/24, 6:30 AM] Srinivas: I signed for my half only. Don't worry\n[19/09/24, 6:31 AM] Srinivas: They gave advance\n[19/09/24, 7:02 AM] Ramesh: For your half only? Send me the copy\n[19/09/24, 7:02 AM] Ramesh: Srinu send the copy\n[25/09/24, 11:11 PM] Ramesh: 6 days. Still no copy\n[14/11/24, 5:47 PM] Ramesh: I got a lawyer notice from Seabreeze saying I agreed to sell. What did you sign Srinu?\n[14/11/24, 5:47 PM] Ramesh: 30 years of friendship\n[14/11/24, 9:12 PM] Srinivas: Talk to my lawyer"},
    {"uploaded": "2025-04-21", "case_ids": ["C2", "C3"], "name": "Legal_notice_Seabreeze_12-11-2024", "kind": "doc",
     "sign": ["V. Harsha Vardhan, Advocate, for Seabreeze Resorts & Hospitality Pvt. Ltd."],
     "pages": [[
         ("r", "VARDHAN LEGAL LLP, Advocates, Siripuram, Visakhapatnam"),
         ("r", "Date: 12.11.2024"),
         ("p", "REGD. POST WITH ACK. DUE"),
         ("p", "To: Sri Ramesh Gorle, S/o late Suryanarayana, Mangamaripeta village, Bheemunipatnam mandal."),
         ("h", "LEGAL NOTICE"),
         ("p", "Under instructions from my client M/s. Seabreeze Resorts & Hospitality Pvt. Ltd., I hereby give you notice as follows:"),
         ("p", "1. You and Sri Srinivas Bandaru agreed to sell land of Ac. 4.20 cents in Sy. No. 112/2, Mangamaripeta, to my client at a meeting held at Hotel Novotel, Visakhapatnam on 10.09.2024, and pursuant thereto an Agreement of Sale dated 18.09.2024 was executed, under which my client paid an advance of Rs. 25,00,000/-."),
         ("p", "2. You have since failed to sign the agreement and have informed third parties that you will not sell."),
         ("p", "3. You are hereby called upon to come forward and execute the registered sale deed within 15 days of receipt of this notice, failing which my client will initiate appropriate legal proceedings, including a suit for specific performance, at your risk as to costs."),
     ]]},
    {"uploaded": "2025-04-21", "case_ids": ["C3"], "name": "Police_petition_acknowledgment_15-04-2025", "kind": "doc", "photo": True,
     "stamp": ["STATION HOUSE OFFICER", "BHEEMUNIPATNAM P.S.", "VISAKHAPATNAM CITY"],
     "sign": ["Writer, Bheemunipatnam P.S."],
     "pages": [[
         ("h", "ANDHRA PRADESH POLICE"),
         ("h", "PETITION RECEIPT / ACKNOWLEDGMENT"),
         ("p", "Petition No.: 211/2025      Date & Time of receipt: 15.04.2025, 11:20 hrs"),
         ("p", "Name of petitioner: Ramesh Gorle, S/o late Suryanarayana, Mangamaripeta."),
         ("p", "Gist of petition: Unknown persons claiming to be from Seabreeze Resorts entered the petitioner's land in Sy. No. 112/2 on 14.04.2025 and erected about 40 cement poles along the west boundary without consent. Requests action."),
         ("p", "Action taken: Received. Enquiry to be made. Civil nature; petitioner advised to approach the competent civil court."),
     ]]},
    {"uploaded": "2025-05-02", "case_ids": ["C1", "C2", "C3"], "name": "1B_ROR_extract_Sy112-2_Mangamaripeta", "kind": "doc",
     "stamp": ["TAHSILDAR", "BHEEMUNIPATNAM MANDAL", "VISAKHAPATNAM DIST."],
     "sign": ["Tahsildar, Bheemunipatnam"],
     "pages": [[
         ("h", "GOVERNMENT OF ANDHRA PRADESH - REVENUE DEPARTMENT"),
         ("h", "RECORD OF RIGHTS (1-B) - EXTRACT"),
         ("p", "District: Visakhapatnam    Mandal: Bheemunipatnam    Village: Mangamaripeta    Khata No.: 1142"),
         ("gap", ""),
         ("p", "Sl. 1 | Sy. No. 112/2 | Pattadar: GORLE RAMESH, S/o Suryanarayana | Extent: Ac. 2.10 | Classification: Dry (Mango/Cashew) | Mutation: Proc. No. B/408/2012 dt. 11.06.2012"),
         ("p", "Sl. 2 | Sy. No. 112/2 | Pattadar: BANDARU SRINIVAS, S/o Appa Rao | Extent: Ac. 2.10 | Classification: Dry | Mutation: Proc. No. B/408/2012 dt. 11.06.2012"),
         ("gap", ""),
         ("p", "Total extent: Ac. 4.20. Enjoyment: Pattadar 1 in possession of the eastern portion with mango trees and a samadhi; Pattadar 2 portion (western) is fallow."),
         ("s", "Certified extract issued on application No. MEE/2025/77812 dated 28.04.2025. Issued on 02.05.2025. Fee paid Rs. 25/-."),
     ]]},
    {"uploaded": "2025-05-02", "case_ids": ["C1", "C2", "C3"], "name": "Encumbrance_Certificate_2011-2025", "kind": "doc",
     "stamp": ["SUB-REGISTRAR", "BHEEMUNIPATNAM", "O/o SRO"],
     "sign": ["Sub-Registrar, Bheemunipatnam"],
     "pages": [[
         ("h", "REGISTRATION AND STAMPS DEPARTMENT, GOVERNMENT OF ANDHRA PRADESH"),
         ("h", "ENCUMBRANCE CERTIFICATE (FORM 15)"),
         ("p", "EC Application No.: 8812/2025   Period searched: 01.01.2011 to 30.04.2025   Property: Sy. No. 112/2, Mangamaripeta village, Ac. 4.20"),
         ("gap", ""),
         ("p", "1. Doc. No. 3417/2011, date of registration 02.03.2011, Nature: Sale. Executant: Kakarla Bhaskara Rao. Claimants: (1) Ramesh Gorle (2) Srinivas Bandaru. Consideration Rs. 30,00,000. Extent Ac. 4.20."),
         ("gap", ""),
         ("p", "No other transaction (sale, mortgage, agreement of sale, general power of attorney) is found registered in respect of the above property during the period searched."),
         ("s", "This certificate is issued on the basis of the index registers; unregistered documents are not reflected. Date of issue: 02.05.2025."),
     ]]},
    {"uploaded": "2025-10-08", "case_ids": ["C1"], "name": "Mediation_failure_report_OS214-2024", "kind": "doc",
     "stamp": ["MEDIATION CENTRE", "DISTRICT COURT", "VISAKHAPATNAM"],
     "sign": ["Sri N. Ravi Shankar, Mediator"],
     "pages": [[
         ("h", "MEDIATION CENTRE, DISTRICT COURT, VISAKHAPATNAM"),
         ("h", "REPORT OF THE MEDIATOR"),
         ("p", "Case: O.S. No. 214 of 2024 on the file of the II Additional Senior Civil Judge, Visakhapatnam. Ramesh Gorle vs Srinivas Bandaru."),
         ("p", "Referred on: 13.08.2025. Sessions held: 26.08.2025, 09.09.2025, 23.09.2025. Both parties attended with counsel."),
         ("p", "Result: FAILED. The defendant insists that the entire property be sold to a third party and proceeds divided. The plaintiff is not willing to sell any part of the property under any circumstances. The parties could not agree even on a division by metes and bounds."),
         ("p", "The matter is returned to the referral court for adjudication."),
     ]]},
    {"uploaded": "2025-06-09", "case_ids": ["C4"], "name": "Rental_agreement_Sri_Durga_Tiffins_2021", "kind": "doc", "photo": True,
     "stamp_paper": ["INDIA NON JUDICIAL", "ANDHRA PRADESH", "Rs. 100   ONE HUNDRED RUPEES"],
     "sign": ["Lakshmi Kantham Peddinti (OWNER)", "Nagaraju Kotla (TENANT)"],
     "pages": [[
         ("h", "RENTAL AGREEMENT"),
         ("p", "This rental agreement is made on 01.06.2021 at Visakhapatnam between Smt. Lakshmi Kantham Peddinti, W/o late P. Satyanarayana, D.No. 50-81-9, Dwaraka Nagar (OWNER) and Sri Nagaraju Kotla, S/o K. Appanna (TENANT)."),
         ("p", "1. The owner lets out the ground floor shop of D.No. 50-81-9, Dwaraka Nagar, measuring about 220 sq. ft., for running a tiffin centre, for a period of 11 months from 01.06.2021, renewable by mutual consent."),
         ("p", "2. Monthly rent Rs. 18,000/- payable on or before the 5th of every month. Advance Rs. 1,00,000/- paid, refundable on vacating after adjusting dues."),
         ("p", "3. The tenant shall not sublet and shall vacate on one month's notice."),
     ]]},
    {"uploaded": "2025-02-20", "case_ids": ["C5"], "name": "Greenfield_purchase_order_04-04-2023", "kind": "doc",
     "stamp": ["GREENFIELD PUBLIC SCHOOL", "PENDURTHI, VSP", "OFFICE"],
     "sign": ["K. Jagan Mohan, Correspondent"],
     "pages": [[
         ("h", "GREENFIELD PUBLIC SCHOOL (CBSE), PENDURTHI, VISAKHAPATNAM"),
         ("r", "Date: 04.04.2023"),
         ("p", "To: M/s. Vijaya Offset Printers, Old Gajuwaka, Visakhapatnam."),
         ("h", "PURCHASE ORDER No. GPS/PO/2023/19"),
         ("p", "Please print and supply the following for academic year 2023-24 as per approved samples: (1) Class 1-10 workbooks, 2,400 copies; (2) Class 6-8 mathematics practice books, 900 copies; (3) long notebooks with school logo, 6,000 nos. Delivery before 31.05.2023."),
         ("p", "Payment: within 60 days of delivery against invoice."),
         ("p", "Estimated value: Rs. 6,80,000/- (approx.)."),
     ]]},
]

# Questions the app must answer (expected answers are for checking, not for upload)
EVAL = [
    ("How much of the beach land does Srinivas say he owns?",
     "It depends where he is saying it. In O.S. 214/2024 (WS 25.06.2025, and as DW1 on 22.07.2026) he claims 70%. In O.S. 57/2025 (WS 11.06.2025, DW1 on 13.05.2026) he says 'equal owners, 50-50'. The 2016 letter and the 1-B also say 2.10 acres each.", ["C1", "C2"]),
    ("Did Seabreeze do any work on the land before the injunction?",
     "Their counter in O.S. 131/2025 (21.05.2025) says 'no construction activity whatsoever; only a survey'. But their plaint and PW1 in O.S. 57/2025 (10.12.2025) say they 'commenced preliminary works in April 2025'. VRO saw ~40 cement poles on 14.04.2025; DW1 admitted 'survey pegs and some poles' on 19.08.2026.", ["C2", "C3"]),
    ("What should I expect from Murthy sir if the other side asks for time again?",
     "He says 'last opportunity' on the second request and imposes costs on the third (Greenfield: Rs 3,000 on 22.06.2026, cross closed). He also refuses irregular filings (Seabreeze SP 09.07.2025: Rs 2,000 costs; memo without copy rejected 11.03.2026).", ["C2", "C3", "C5"]),
    ("Is Padmavathi madam strict about adjournments?",
     "No. She granted repeated time to Harinath without costs (14.05.2025), forgave our own missed summons on 25.03.2026, referred the friends' case to mediation, and gave the tenant extra time to deposit.", ["C1", "C4"]),
    ("What is pending from our side?",
     "Objections to I.A. 1187/2026 in the Seabreeze SP suit, undertaken to be filed by 30.09.2026: draft only 60% on 24.09 and waiting for EC, so overdue on 5 Oct. Continue the DW1 cross in the injunction suit on 5 Oct using the plaint para 3 (certified copy to be got by Divya). Written arguments in Greenfield. Tiffin centre: September instalment unpaid, letter first, then execution petition if unpaid by 25th.", ["C2", "C3", "C4", "C5"]),
    ("Who is the VRO and what did he say?",
     "Appala Naidu. In the injunction suit (10.06.2026): saw about 40 cement poles on 14.04.2025, and Seabreeze jeep AP 31 CX 4417. In the partition suit (03.06.2026): 1-B shows 2.10 acres each, Ramesh's family cultivates the east half where his father's grave is.", ["C1", "C3"]),
    ("Did Ramesh ever sign the Seabreeze agreement?",
     "No. His signature column is blank; the company director admitted it in cross (04.02.2026). The EC shows no GPA registered. His WhatsApp on 10.09.2024 says 'Don't sign anything for me.'", ["C2"]),
]
